Feat: build docker images when a new release is created
FLock-io/llm-loss-validator pull request #24
Opened 2024-06-14 16:09 UTC by zJuuu

This PR adds a workflow that automatically creates the Docker image when a new release is created.

After merge you have to add a secret GH_PAT to the repository with the value of a personal access token with repo, write:packages and delete:packages scopes.

The first successful build will be private. You have to assign it manually to this repository and change the visibility of the package to public.

Address: 0x493FBf42777B6CE24B1c018c38D1A24C7572904F

2024-06-16 16:38 UTC, nickcom007 requested changes

2024-06-16 16:38 UTC, nickcom007 commented on .github/workflows/publish-ghcr.yml
> +  build-and-push-image-normal:
I think we can remove this for now. People barely use the CPU version

2024-06-16 16:38 UTC, nickcom007 commented on .github/workflows/publish-ghcr.yml
> +          Dockerfile: Dockerfile.gpu
Use `file` instead of `Dockerfile` to be consistent with the documentation.
https://docs.docker.com/build/ci/github-actions/

2024-06-16 16:38 UTC, nickcom007 commented on .github/workflows/publish-ghcr.yml
> +        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
Any specific reason to use `@65b78e6e13532edd9afa3aa52ac7964289d1a9c1` instead of something like `@v3`

2024-06-16 16:54 UTC, nickcom007 requested changes

2024-06-16 16:54 UTC, nickcom007 commented on .github/workflows/publish-ghcr.yml
> +  IMAGE_NAME: ${{ github.repository }}
The `IMAGE_NAME` is defined here and then lowered in a step, seems a bit redudant. We can define this in a single step?

2024-06-17 11:53 UTC, zJuuu commented
Thanks for the change requests. I have implemented and tested them and changed the version name to the tag name instead of the commit hash.

2024-06-18 16:43 UTC, nickcom007 approved these changes

2024-06-18 16:43 UTC, nickcom007 commented
LGTM

2024-06-18 16:43 UTC, merged